apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "backend-consul.name" . }}-vault-acl
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "backend-consul.name" . }}
    chart: {{ template "backend-consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
spec:
  template:
    metadata:
      name: {{ template "backend-consul.name" . }}-vault-acl-init
      labels:
        app: {{ template "backend-consul.name" . }}
        chart: {{ template "backend-consul.chart" . }}
        release: {{ .Release.Name }}
        component: consul-vault-acl-init
      annotations:
        "consul.hashicorp.com/connect-inject": "false"
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Release.Name }}-consul-server-acl-init
      containers:
        - name: vault-acl
          image: {{ .Values.global.image }}
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: CONSUL_HTTP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-consul-bootstrap-acl-token
                  key: token
          command:
            - "/bin/sh"
            - "-ec"
            - |
              export CONSUL_HTTP_ADDR="${HOST_IP}:8500"
              consul acl policy create -name vault-service -rules @/consul/aclconfig/vault.json
              consul acl token create -description "Token for Vault" -policy-name vault-service          
          volumeMounts:
            - name: aclconfig
              mountPath: /consul/aclconfig
      volumes:
        - name: aclconfig
          configMap:
            name: {{ template "backend-consul.name" . }}-vault-acl-config
